name: relief_haven_mobile
description: "Relief Haven mobile app"
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  objectbox: any
  objectbox_flutter_libs: any
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  dio: any
  riverpod: any
  flutter_riverpod: any
  shared_preferences: any
  google_fonts: ^8.0.2
  shimmer: any
  connectivity_plus: any
  intl: any
  flutter_dotenv: any
  geolocator: any
  supabase_flutter: any
  logger: any
  flutter_map: ^8.3.0
  flutter_map_animations: any
  latlong2: any
  toastification: any
  flutter_native_splash: ^2.4.7
  chat_bubbles: any
  flutter_markdown_plus: any
  flutter_map_tile_caching: ^10.1.1
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

flutter_native_splash:
  android: true
  ios: true
  fullscreen: true

  color: '#31628D'
  image: 'assets/images/compass_dark.png'
  color_dark: '#9DCBFB'
  image_dark: 'assets/images/compass_splash.png'

  android_12:
    image: 'assets/images/compass_dark.png'
    image_dark: 'assets/images/compass_splash.png'
    color: '#31228D'
    color_dark: '#9DCBFB'
