import 'geo_point_model.dart';

class NavLogModel {
  final String navigationId;
  final String userId;
  final String shelterId;
  final GeoPointModel? location;
  final double distance;
  final DateTime navigationDate;

  NavLogModel({
    required this.navigationId,
    required this.userId,
    required this.shelterId,
    this.location,
    required this.distance,
    required this.navigationDate,
  });

  factory NavLogModel.fromJson(Map<String, dynamic> json) {
    final locationJson = json['location'];
    return NavLogModel(
      navigationId: json['navigation_id'] as String,
      userId: json['user_id'] as String,
      shelterId: json['shelter_id'] as String,
      location: locationJson is Map<String, dynamic>
          ? GeoPointModel.fromJson(locationJson)
          : null,
      distance: (json['distance'] as num).toDouble(),
      navigationDate: DateTime.parse(json['navigation_date'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'navigation_id': navigationId,
      'user_id': userId,
      'shelter_id': shelterId,
      'location': location?.toJson(),
      'distance': distance,
      'navigation_date': navigationDate.toIso8601String(),
    };
  }

  NavLogModel copyWith({
    String? navigationId,
    String? userId,
    String? shelterId,
    GeoPointModel? location,
    double? distance,
    DateTime? navigationDate,
  }) {
    return NavLogModel(
      navigationId: navigationId ?? this.navigationId,
      userId: userId ?? this.userId,
      shelterId: shelterId ?? this.shelterId,
      location: location ?? this.location,
      distance: distance ?? this.distance,
      navigationDate: navigationDate ?? this.navigationDate,
    );
  }
}

/// Request payload for creating a navigation log.
/// navigation_date is generated by the backend.
class NavigationLogCreateRequest {
  final String shelterId;
  final GeoPointModel location;
  final double distance;

  const NavigationLogCreateRequest({
    required this.shelterId,
    required this.location,
    required this.distance,
  });

  Map<String, dynamic> toJson() {
    return {
      'shelter_id': shelterId,
      'location': location.toJson(),
      'distance': distance,
    };
  }
}
